version: "3.9"
services:
  controller:
    hostname: controller
    image: spxcloudevops/ansible-playground-controller
    restart: always
    ports:
      - '8090:9090'
  web:
    image: spxcloudevops/ansible-playground-web
    restart: always
    depends_on:
      - controller
      - worker1
      - worker2
      - worker3
    ports:
      - '8080:80'
    volumes:
      - controller-root:/root
  ubuntu:
    hostname: ubuntu
    image: spxcloudevops/ansible-playground-ubuntu-worker
    restart: always
    ports: 
      - '8091:9090'
      - '2291:22'
    volumes:
      - ubuntu-root:/root
  alpine:
    hostname: alpine
    image: spxcloudevops/ansible-playground-alpine-worker
    restart: always
    ports: 
      - '8092:9090'
      - '2292:22'
    volumes:
      - alpine-root:/root
  centos:
    hostname: centos
    image: spxcloudevops/ansible-playground-centos-worker
    restart: always
    ports: 
      - '8093:9090'
      - '2293:22'
    volumes:
      - centos-root:/root
volumes:
  controller-root:
  ubuntu-root:
  alpine-root:
  centos-root: