version: "3.9"
services:
  controller:
    hostname: controller
    image: spxcloudevops/ansible-playground-controller
    restart: always
    ports:
      - '8090:9090'
    volumes:
      - ./controller-root:/root
  web:
    image: spxcloudevops/ansible-playground-web
    restart: always
    depends_on:
      - controller
      - worker1
      - worker2
      - worker3
    ports:
      - '8080:80'
  ubuntu01:
    hostname: ubuntu01
    image: spxcloudevops/ansible-playground-ubuntu-worker
    restart: always
    ports: 
      - '8091:9090'
      - '2291:22'
    volumes:
      - ubuntu-root:/root
  ubuntu02:
    hostname: ubuntu02
    image: spxcloudevops/ansible-playground-ubuntu-worker
  ubuntu03:
    hostname: ubuntu03
    image: spxcloudevops/ansible-playground-ubuntu-worker
  alpine01:
    hostname: alpine01
    image: spxcloudevops/ansible-playground-alpine-worker
    restart: always
    ports: 
      - '8092:9090'
      - '2292:22'
    volumes:
      - alpine-root:/root
  alpine02:
    hostname: alpine02
    image: spxcloudevops/ansible-playground-alpine-worker
  alpine03:
    hostname: alpine03
    image: spxcloudevops/ansible-playground-alpine-worker
  centos01:
    hostname: centos01
    image: spxcloudevops/ansible-playground-centos-worker
    restart: always
    ports: 
      - '8093:9090'
      - '2293:22'
    volumes:
      - centos-root:/root
  centos02:
    hostname: centos02
    image: spxcloudevops/ansible-playground-centos-worker
  centos03:
    hostname: centos03
    image: spxcloudevops/ansible-playground-centos-worker
volumes:
  ubuntu-root:
  alpine-root:
  centos-root: