version: "3.9"
services:
  controller:
    hostname: controller
    image: spxcloudevops/ansible-playground-controller
    restart: always
    ports:
      - '8090:9090'
    volumes:
      - ./controller-root:/root
  web:
    image: spxcloudevops/ansible-playground-web
    restart: always
    depends_on:
      - controller
      - worker1
      - worker2
      - worker3
    ports:
      - '8080:80'
  ubuntu01:
    hostname: ubuntu01
    image: spxcloudevops/ansible-playground-ubuntu-worker
    restart: always
    ports: 
      - '8191:9090'
    volumes:
      - ubuntu-root01:/root
  ubuntu02:
    hostname: ubuntu02
    image: spxcloudevops/ansible-playground-ubuntu-worker
    restart: always
    ports: 
      - '8192:9090'
    volumes:
      - ubuntu-root02:/root

  ubuntu03:
    hostname: ubuntu03
    image: spxcloudevops/ansible-playground-ubuntu-worker
    restart: always
    ports: 
      - '8193:9090'
    volumes:
      - ubuntu-root03:/root

  alpine01:
    hostname: alpine01
    image: spxcloudevops/ansible-playground-alpine-worker
    restart: always
    ports: 
      - '8291:9090'
    volumes:
      - alpine-root01:/root
  alpine02:
    hostname: alpine02
    image: spxcloudevops/ansible-playground-alpine-worker
    restart: always
    ports: 
      - '8292:9090'
    volumes:
      - alpine-root02:/root
  alpine03:
    hostname: alpine03
    image: spxcloudevops/ansible-playground-alpine-worker
    restart: always
    ports: 
      - '8293:9090'
    volumes:
      - alpine-root03:/root
  centos01:
    hostname: centos01
    image: spxcloudevops/ansible-playground-centos-worker
    restart: always
    ports: 
      - '8391:9090'
    volumes:
      - centos-root01:/root
  centos02:
    hostname: centos02
    image: spxcloudevops/ansible-playground-centos-worker
    restart: always
    ports: 
      - '8392:9090'
    volumes:
      - centos-root02:/root
  centos03:
    hostname: centos03
    image: spxcloudevops/ansible-playground-centos-worker
    restart: always
    ports: 
      - '8393:9090'
    volumes:
      - centos-root03:/root
volumes:
  ubuntu-root01:
  ubuntu-root02:
  ubuntu-root03:
  alpine-root01:
  alpine-root02:
  alpine-root03:
  centos-root01:
  centos-root02:
  centos-root03: