name: Build and publish Web

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'

jobs:
  push_to_registry:
    name: Build and publish Web
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: ...

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./web
          push: true
          tags: spxcloudevops/ansible-playground-web
